# Use an OpenJDK base image
FROM openjdk:11-jre-slim

# Copy the compiled Java application (you will compile it later) into the container
COPY target/PostgreSQLJDBCExample.jar /app/PostgreSQLJDBCExample.jar

# Run the Java application
ENTRYPOINT ["java", "-jar", "/app/PostgreSQLJDBCExample.jar"]
