insert into student values (92, 1, 10, 'Amit', 'Delhi Public School');
insert into student values (78, 2, 12, 'Priya', 'DAV School');
insert into student values (85, 3, 11, 'Ravi', 'St. Xaviers School');
insert into student values (90, 4, 10, 'Neha', 'Seth M.R. Jaipuria School');
insert into student values (68, 5, 11, 'Rahul', 'Ryan International School');
insert into student values (77, 6, 12, 'Ayesha', 'Jamnabai Narsee School');
insert into student values (88, 7, 10, 'Vikas', 'Holy Family School');
insert into student values (81, 8, 12, 'Sneha', 'The Heritage School');
insert into student values (74, 9, 10, 'Manish', 'Mount Carmel School');
insert into student values (89, 10, 11, 'Pooja', 'Kendriya Vidyalaya');
insert into student values (76, 11, 12, 'Siddharth', 'Delhi Public School');
insert into student values (82, 12, 10, 'Isha', 'DAV School');
insert into student values (88, 13, 11, 'Rohit', 'St. Xaviers School');
insert into student values (75, 14, 10, 'Anjali', 'Seth M.R. Jaipuria School');
insert into student values (84, 15, 12, 'Karan', 'Ryan International School');
insert into student values (92, 16, 11, 'Shreya', 'Jamnabai Narsee School');
insert into student values (90, 17, 10, 'Nikhil', 'Holy Family School');
insert into student values (78, 18, 12, 'Riya', 'The Heritage School');
insert into student values (80, 19, 11, 'Aarav', 'Mount Carmel School');
insert into teacher values (10, 'Seema Pathak');
insert into teacher values (11, 'Anand Shinde');
insert into teacher values (12, 'Navin Kumar');